trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'
    appType: 'webApp'
    appName: 'myfirstprojectapplication'
    package: '.'